#!/usr/bin/env bash

profile='persona-builder'
artifacts_bucket='s3://persona-builder-artifacts'
contracts='loom-contracts'
contracts_dir="./public/json/contracts"
([ -d $contracts_dir ] || mkdir $contracts_dir) && pushd $contracts_dir > /dev/null

aws --profile "$profile" --region 'us-east-1' s3 cp $artifacts_bucket/$contracts . \
    && \
tar -xvzf $contracts \
    && \
rm $contracts

retval=$?
popd > /dev/null
err_msg='Could not update solidity contracts. Exiting.'
([ $retval -ne 0 ] && echo "$err_msg") || node start.js
